
spring:
  application:
    name: iot-monitor

  datasource:
    url: jdbc:postgresql://localhost:5432/iotdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true   # włączenie migracji bazy
    locations: classpath:db/migration  # lokalizacja plików SQL
    validate-migration-naming: true  #kontrola nazw migracji
  jpa:
    hibernate:
      ddl-auto: none # brak automatycznego tworzenia tabel (Flyway zarządza schematem)
    show-sql: true # wyświetlanie zapytań SQL w logach
    properties:
      hibernate:
        format_sql: true # czytelne formatowanie SQL
  jackson:
    serialization:
      write-dates-as-timestamps: false  # daty w JSON jako ISO-8601 (czytelny format)

server:
  port: 8080 # port aplikacji backend

logging:
  level:
    org.hibernate.SQL: DEBUG # logowanie zapytań SQL
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE # logowanie parametrów SQL